In [1]:
import json
import pandas as pd
import numpy as np
# from matminer.datasets import load_dataset
# from modnet.models import MODNetModel
# from modnet.preprocessing import MODData
import matplotlib.pyplot as plt 
from pymatgen.core import Composition
import json


file_path = 'bandgap_target_clusters50.json'
ncluster=50
featurefile = 'bandgap_features.csv'
property_column='gap expt'
with open(file_path, 'r') as file:
    cluster_ids = json.load(file)
    
df2 = pd.read_csv(featurefile)
y = df2['gap expt'].values
excluded = ["formula", "composition", "formula", "gap expt"]
X = df2.drop(excluded, axis=1)

for i, cluster_id in enumerate(range(0,ncluster)):
    target_id_list = cluster_ids[str(cluster_id)]

    Xt = X.iloc[target_id_list]
    yt = df2["gap expt"].iloc[target_id_list].values

    Xs = X.drop(target_id_list)
    ys = df2["gap expt"].drop(target_id_list).values
    break

In [13]:
Xt

,Unnamed: 0,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
4470,4470,30.0,52.0,22.0,41.000000,10.990000,30.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,64.0,194.0,130.0,172.420000,21.364200,152.0
4465,4465,30.0,80.0,50.0,42.500000,11.750000,52.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,152.0,194.0,42.0,172.160000,20.529600,152.0
4464,4464,30.0,80.0,50.0,43.000000,11.960000,52.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,152.0,194.0,42.0,171.880000,20.350400,152.0
4476,4476,30.0,80.0,50.0,43.500000,12.150000,52.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,152.0,194.0,42.0,171.600000,20.160000,152.0
4461,4461,30.0,80.0,50.0,44.500000,12.470000,52.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,152.0,194.0,42.0,171.040000,19.745600,152.0
4463,4463,30.0,80.0,50.0,46.000000,12.800000,52.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,152.0,194.0,42.0,170.200000,19.040000,152.0
4424,4424,50.0,70.0,20.0,56.000000,7.000000,52.0,39.0,90.0,51.0,...,0.0,0.0,0.0,0.0,141.0,225.0,84.0,167.500000,28.750000,152.0
4496,4496,16.0,30.0,14.0,22.615385,6.816568,30.0,69.0,94.0,25.0,...,0.0,0.0,0.0,0.0,64.0,194.0,130.0,126.307692,62.485207,194.0
4446,4446,30.0,80.0,50.0,61.000000,15.200000,52.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,152.0,194.0,42.0,161.800000,9.800000,152.0
4467,4467,30.0,34.0,4.0,32.000000,1.990000,30.0,69.0,89.0,20.0,...,0.0,0.0,0.0,0.0,14.0,194.0,180.0,104.110000,89.610000,14.0
4472,4472,30.0,34.0,4.0,32.000000,1.900000,30.0,69.0,89.0,20.0,...,0.0,0.0,0.0,0.0,14.0,194.0,180.0,105.100000,86.100000,14.0

In [14]:
Xt[8:]

,Unnamed: 0,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
4446,4446,30.0,80.0,50.0,61.0,15.20,52.0,69.0,90.0,21.0,...,0.0,0.0,0.0,0.0,152.0,194.0,42.0,161.80,9.80,152.0
4467,4467,30.0,34.0,4.0,32.0,1.99,30.0,69.0,89.0,20.0,...,0.0,0.0,0.0,0.0,14.0,194.0,180.0,104.11,89.61,14.0
4472,4472,30.0,34.0,4.0,32.0,1.90,30.0,69.0,89.0,20.0,...,0.0,0.0,0.0,0.0,14.0,194.0,180.0,105.10,86.10,14.0

In [12]:
from sklearn.metrics import balanced_accuracy_score
y_true = [1,1]
y_pred = [0,0]
balanced_accuracy_score(y_true, y_pred)

/home/rongzhid/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2006: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

0.0